'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Booking

    '''<summary>
    '''lblBookingType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBookingType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''adsTherapistList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adsTherapistList As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''rptTherapists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTherapists As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblTherapist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTherapist As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTherapists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTherapists As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvTherapist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTherapist As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''adsTherapists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adsTherapists As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''adsTimeSlots control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adsTimeSlots As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''lblTimeSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeSlot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTimeSlots control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTimeSlots As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvTimeSlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTimeSlot As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''adsCheckBooking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adsCheckBooking As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''lblFileUploadInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileUploadInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileUpload As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fuReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuReport As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblFileUploadError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileUploadError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LblConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblConfirmation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''adsBooking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adsBooking As Global.System.Web.UI.WebControls.AccessDataSource
End Class
