'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Quiz

    '''<summary>
    '''rblFreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblFreq As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList7 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList8 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList9 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList10 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList11 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList12 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList13 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList14 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList15 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList16 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList17 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList18 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList19 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RadioButtonList20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList20 As Global.System.Web.UI.WebControls.RadioButtonList
End Class
